# @package _global_
name: reveal
gpu: 1
dataset:
  name: example
  token:
    max_parts: 50
    is_wrapped: false
    is_splitted: false
    vocabulary_size: 190000

ggnn:
  hidden_size: 128
  layer_num: 5

classifier:
  hidden_size: 256
  n_hidden_layers: 1
  drop_out: 0.2
  activation: relu

hyper_parameters:
  vector_length: 100

  n_epochs: 100
  patience: 10
  save_epoch: 5
  batch_size: 64
  test_batch_size: 64
  reload_dataloader: true
  clip_norm: 2.0
  random_context: true
  shuffle_data: true
  log_interval: 1
  
  optimizer: "Adam"
  nesterov: true
  learning_rate: 0.001
  weight_decay: 0
  beta1: 0.9
  beta2: 0.999
  decay_gamma: 0.95
cl:
  n_epochs: 30
  cv_n_folds: 5
  batch_size: 64
  thresholds: 0.7
dt:
  ds_count: 500
  drop_out: 0.5
  n_epochs: 20
  delta: 0.001
  vote_rate: 0.5
  contamination: 0.1
  model_name: "reveal"